services:
  - type: web
    name: order-send-to-minimax
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
    healthCheckPath: /health
    autoDeploy: true 